# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true

# Spring Boot
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
  jta:
    log-dir: ./target/tx-object-store
    narayana:
      periodicRecoveryPeriod: 10
      recoveryBackoffPeriod: 1
      defaultTimeout: 300
      recoveryDbUser: ${spring.datasource.username}
      recoveryDbPass: ${spring.datasource.password}
      recoveryJmsUser: ${spring.artemis.user}
      recoveryJmsPass: ${spring.artemis.password}
  artemis:
    mode: NATIVE
    host: localhost
    port: 61616
    user: admin
    password: admin
    embedded.enabled: false
  datasource:
    xa.dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
    url: jdbc:mysql://localhost:3306/example?autoReconnect=true&useSSL=false
    username: root
    password: Abcd1234
    schema: classpath:META-INF/sql/schema.sql
    schemaUsername: ${spring.datasource.username}
    schemaPassword: ${spring.datasource.password}

# Camel Spring Boot
camel:
  springboot:
    name: CamelSpringBootXa
    main-run-controller: true
  component:
    jms:
      recoveryInterval: 30000

# Logging
logging:
  level:
    #com.arjuna: DEBUG

# Application
application:
  file:
    messagesDirectory: target/messages
  jms:
    messagesQueue: org.apache.camel.examples.MESSAGES
  sql:
    messagesTable: MESSAGES