apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: camel-spring-boot-xa-configmap
data:
  application.properties: |-
    spring.jta.log-dir: /mnt/tx-object-store
    spring.artemis.host: 192.168.99.1
    spring.artemis.port: 61616
    spring.datasource.url: jdbc:mysql://192.168.99.1:3306/example?autoReconnect=true&useSSL=false
    application.file.messages-directory: /mnt/messages